### PR TITLE
read-only enketo view for records #460

### PR DESCRIPTION
**Pull request by awemulya**
This Allows you Read only View of submissions In Enketo.

### CODE REVIEW

**Comment by raeesaroj** [comment]
since in common.py (https://github.com/kobotoolbox/kobocat/blob/master/onadata/settings/common.py), default ENKETO_VERSION is 'legacy' 
`ENKETO_VERSION= os.environ.get('ENKETO_VERSION', 'Legacy').lower()`
You need to make ENKETO_VERSION to 'express' and this works perfectly.

**Comment by awemulya** [comment]
Yeah you need to make
os.environ["ENKETO_VERSION"] = 'express' 
in your local_settings.py
thank you @raeesaroj

**Comment by awemulya** [comment]
Yeah you need to make
os.environ["ENKETO_VERSION"] = 'express' 
in your local_settings.py
thank you @raeesaroj

**Comment by awemulya** [comment]
https://github.com/kobotoolbox/kobocat/pull/537/commits/64524f563adf093a40d13266a1fd60737c9e1f07
Host for debug=False need to be implemented.

**Comment by awemulya** [comment]
@jnm @magicznyleszek How can I set code  reviewer for this PR.

**Comment by jnm** [comment]
@awemulya, thank you so much for the contribution, but we're planning to remove all UI from KoBoCAT in the future and use it only as an OpenRosa server: https://community.kobotoolbox.org/t/contemplating-the-future-of-kobocat/2743.

We hope to do justice to your work at https://github.com/kobotoolbox/kpi/issues/2607 by adding a read-only Enketo view to KPI.

**Pull request closed without merging**
