### PR TITLE
Fixed Instance set_deleted to use current time when deleted_at is not passed

### LINKED ISSUE #472: `_deleted_at` incorrectly set to the date the server last started, not the actual deletion time
very common python mistake: https://github.com/kobotoolbox/kobocat/blob/1973fb07d21c403e75d52719d4739a896a6b1bf1/onadata/apps/logger/models/instance.py#L377-L382

### PR DESCRIPTION
**Pull request by ajarocki**
Fixes #472

### CODE REVIEW

**Comment by jnm** [comment]
Thank you for the contribution. This use of `Ellipsis` doesn't seem consistent with the Python documentation: https://docs.python.org/2/library/constants.html#Ellipsis. Would you be willing to rewrite your patch to use `None`?

**Comment by ajarocki** [comment]
Sure I can, but does it make sense in this case? Note that without this change passing `None` seems valid, especially if `Instance.deleted_at` was set to some date already and a call with `None` would set it back to not deleted. If `None` is used as "no value was passed, use the default", the option to clear `deleted_at` is gone.

Ideally instead of `Ellipsis` there would be an equivalent of `undefined` - then it would be clear that the default value should be used. But maybe this special case I mentioned never happens and should not be allowed, then for sure `None` makes sense.

**Comment by jnm** [comment]
It looks like there are 3 places in the code where `set_deleted()` is called, and none of them use it to clear `deleted_at`. That quick search also revealed `set_deleted_at()`, another method of the same class that needs to be fixed:
https://github.com/kobotoolbox/kobocat/blob/4c5c40f6167cd41a0ffa9a9ed287c2d7cdd5d71c/onadata/apps/logger/models/instance.py#L165-L172

I see your point, though, and a few ways of working around it come to mind: use something like `False` as the default value, which could never be mistaken for a `datetime` or null in a database, or turn to this paradigm:
```python
def set_deleted(self, **kwargs):
    try:
        self.deleted_at = kwargs['deleted_at']
    except KeyError:
        self.deleted_at = timezone.now()
```

tbh, KoBoToolbox has abandoned `deleted_at` altogether after we discovered that it's called only by the [legacy view](https://github.com/kobotoolbox/kobocat/blob/82111fabc5824bf06ad73c7666919972d03f479d/onadata/apps/main/views.py#L1247), which we intend to remove, and not by the [data API](https://github.com/kobotoolbox/kobocat/blob/82111fabc5824bf06ad73c7666919972d03f479d/onadata/apps/api/viewsets/data_viewset.py#L581-L598). It also seems more consistent with people's expectations (and perhaps regulations) to really erase data when instructed to do so.

**Comment by ajarocki** [comment]
I took another approach - just defining new constant object called `UNDEFINED`. That way using `is` comparison will have the exact effect we want, behavior won't be changed and function signature will be explicit. Of course we can use one any of the above versions you proposed as well.

Abandoning the issue due to reasons outlined above could work too, but I'm not sure I agree with removing all traces of previously existing instance. This approach becomes troublesome when trying to sync other services via api. I'm not aware of a good way to sync deleted instances without fetching everything, or checking one by one if that still exists. However if deleted instances were kept in database (with metadata only and deleted_at set, xml contents empty) the synchronization would be way easier. But maybe that's a topic for another issue.

**Comment by jnm** [comment]
Thank you again for the contribution. I am closing this PR because `deleted_at` has been fully removed as of #732 and #744.

**Pull request closed without merging**
